# wind更新表 id
Wind:
    wind_id:
        daily: {'中国10年期国债':'M1001654', '美国10年期国债':'G0000891','日本10年期国债':'G1235664',
             '德国10年期国债':'B2559386','英国10年期国债':'G0006353','法国10年期国债':'G1400003'}

Fred:
    fred_id:
        daily:
Wind_Table:
    global_index:
        daily:
        weekly: {'上证指数': '000001.SH', '上证50': '000016.SH', '科创50': '000688.SH',
        '中证500': '000905.SH', '中证800': '000906.SH', '中证1000': '000852.SH',
        '沪深300指数': '000300.SH',
        '标普500': 'SPX.GI', '道琼斯工业指数': 'DJI.GI', '纳斯达克指数': 'IXIC.GI',
        '恒生指数': 'HSI.HI', '日经225': 'N225.GI', '德国DAX': 'GDAXI.GI', '法国CAC40': 'FCHI.GI', '英国富时100': 'FTSE.GI'}
    individual_table:
