from datetime import datetime

from peewee import *

from ..mysql_peewee import connect_mysql, dict2str, handle_table

# 当前时间
now = datetime.now()
# 链接数据库
mysql_db = connect_mysql(database='ks_db')


class CFTCDisaggFuture(Model):
    date = DateField(column_name='date', help_text='统计日期')
    symbol = CharField(column_name='symbol', null=True, help_text='合约名称')
    contract_market_code = CharField(column_name='contract_market_code', null=False, help_text='合约代码')
    change_in_m_money_long_all = FloatField(column_name='change_in_m_money_long_all', null=True, help_text='')
    change_in_m_money_short_all = FloatField(column_name='change_in_m_money_short_all', null=True)
    change_in_m_money_spread_all = FloatField(column_name='change_in_m_money_spread_all', null=True)
    change_in_nonrept_long_all = FloatField(column_name='change_in_nonrept_long_all', null=True)
    change_in_nonrept_short_all = FloatField(column_name='change_in_nonrept_short_all', null=True)
    change_in_open_interest_all = FloatField(column_name='change_in_open_Interest_all', null=True)
    change_in_other_rept_long_all = FloatField(column_name='change_in_other_rept_long_all', null=True)
    change_in_other_rept_short_all = FloatField(column_name='change_in_other_rept_short_all', null=True)
    change_in_other_rept_spread_all = FloatField(column_name='change_in_other_rept_spread_all', null=True)
    change_in_prod_merc_long_all = FloatField(column_name='change_in_prod_merc_long_all', null=True)
    change_in_prod_merc_short_all = FloatField(column_name='change_in_prod_merc_short_all', null=True)
    change_in_swap_long_all = FloatField(column_name='change_in_swap_long_all', null=True)
    change_in_swap_short_all = FloatField(column_name='change_in_swap_short_all', null=True)
    change_in_swap_spread_all = FloatField(column_name='change_in_swap_spread_all', null=True)
    change_in_tot_rept_long_all = FloatField(column_name='change_in_tot_rept_long_all', null=True)
    change_in_tot_rept_short_all = FloatField(column_name='change_in_tot_rept_short_all', null=True)
    conc_gross_le_4_tdr_long_all = FloatField(column_name='conc_gross_le_4_tdr_long_all', null=True)
    conc_gross_le_4_tdr_short_all = FloatField(column_name='conc_gross_le_4_tdr_short_all', null=True)
    conc_gross_le_8_tdr_long_all = FloatField(column_name='conc_gross_le_8_tdr_long_all', null=True)
    conc_gross_le_8_tdr_short_all = FloatField(column_name='conc_gross_le_8_tdr_short_all', null=True)
    conc_net_le_4_tdr_long_all = FloatField(column_name='conc_net_le_4_tdr_long_all', null=True)
    conc_net_le_4_tdr_short_all = FloatField(column_name='conc_net_le_4_tdr_short_all', null=True)
    conc_net_le_8_tdr_long_all = FloatField(column_name='conc_net_le_8_tdr_long_all', null=True)
    conc_net_le_8_tdr_short_all = FloatField(column_name='conc_net_le_8_tdr_short_all', null=True)
    m_money_positions_long_all = IntegerField(column_name='m_money_positions_long_all', null=True)
    m_money_positions_short_all = IntegerField(column_name='m_money_positions_short_all', null=True)
    m_money_positions_spread_all = IntegerField(column_name='m_money_positions_spread_all', null=True)
    nonrept_positions_long_all = IntegerField(column_name='nonrept_positions_long_all', null=True)
    nonrept_positions_short_all = IntegerField(column_name='nonrept_positions_short_all', null=True)
    open_interest_all = IntegerField(column_name='open_Interest_all', null=True)
    other_rept_positions_long_all = IntegerField(column_name='other_rept_positions_long_all', null=True)
    other_rept_positions_short_all = IntegerField(column_name='other_rept_positions_short_all', null=True)
    other_rept_positions_spread_all = IntegerField(column_name='other_rept_positions_spread_all', null=True)
    pct_of_oi_m_money_long_all = FloatField(column_name='pct_of_oi_m_money_long_all', null=True)
    pct_of_oi_m_money_short_all = FloatField(column_name='pct_of_oi_m_money_short_all', null=True)
    pct_of_oi_m_money_spread_all = FloatField(column_name='pct_of_oi_m_money_spread_all', null=True)
    pct_of_oi_nonrept_long_all = FloatField(column_name='pct_of_oi_nonrept_long_all', null=True)
    pct_of_oi_nonrept_short_all = FloatField(column_name='pct_of_oi_nonrept_short_all', null=True)
    pct_of_oi_other_rept_long_all = FloatField(column_name='pct_of_oi_other_rept_long_all', null=True)
    pct_of_oi_other_rept_short_all = FloatField(column_name='pct_of_oi_other_rept_short_all', null=True)
    pct_of_oi_other_rept_spread_all = FloatField(column_name='pct_of_oi_other_rept_spread_all', null=True)
    pct_of_oi_prod_merc_long_all = FloatField(column_name='pct_of_oi_prod_merc_long_all', null=True)
    pct_of_oi_prod_merc_short_all = FloatField(column_name='pct_of_oi_prod_merc_short_all', null=True)
    pct_of_oi_swap_long_all = FloatField(column_name='pct_of_oi_swap_long_all', null=True)
    pct_of_oi_swap_short_all = FloatField(column_name='pct_of_oi_swap_short_all', null=True)
    pct_of_oi_swap_spread_all = FloatField(column_name='pct_of_oi_swap_spread_all', null=True)
    pct_of_oi_tot_rept_long_all = FloatField(column_name='pct_of_oi_tot_rept_long_all', null=True)
    pct_of_oi_tot_rept_short_all = FloatField(column_name='pct_of_oi_tot_rept_short_all', null=True)
    pct_of_open_interest_all = IntegerField(column_name='pct_of_open_Interest_all', null=True)
    prod_merc_positions_long_all = IntegerField(column_name='prod_merc_positions_long_all', null=True)
    prod_merc_positions_short_all = IntegerField(column_name='prod_merc_positions_short_all', null=True)
    swap_positions_long_all = IntegerField(column_name='swap_positions_long_all', null=True)
    swap_positions_short_all = IntegerField(column_name='swap_positions_short_all', null=True)
    swap_positions_spread_all = IntegerField(column_name='swap_positions_spread_all', null=True)
    tot_rept_positions_long_all = IntegerField(column_name='tot_rept_positions_long_all', null=True)
    tot_rept_positions_short_all = IntegerField(column_name='tot_rept_positions_short_all', null=True)
    traders_m_money_long_all = FloatField(column_name='traders_m_money_long_all', null=True)
    traders_m_money_short_all = FloatField(column_name='traders_m_money_short_all', null=True)
    traders_m_money_spread_all = FloatField(column_name='traders_m_money_spread_all', null=True)
    traders_other_rept_long_all = FloatField(column_name='traders_other_rept_long_all', null=True)
    traders_other_rept_short_all = FloatField(column_name='traders_other_rept_short_all', null=True)
    traders_other_rept_spread_all = FloatField(column_name='traders_other_rept_spread_all', null=True)
    traders_prod_merc_long_all = FloatField(column_name='traders_prod_merc_long_all', null=True)
    traders_prod_merc_short_all = FloatField(column_name='traders_prod_merc_short_all', null=True)
    traders_swap_long_all = FloatField(column_name='traders_swap_long_all', null=True)
    traders_swap_short_all = FloatField(column_name='traders_swap_short_all', null=True)
    traders_swap_spread_all = FloatField(column_name='traders_swap_spread_all', null=True)
    traders_tot_all = IntegerField(column_name='traders_tot_all', null=True)
    traders_tot_rept_long_all = IntegerField(column_name='traders_tot_rept_long_all', null=True)
    traders_tot_rept_short_all = IntegerField(column_name='traders_tot_rept_short_all', null=True)
    op_time = DateTimeField(column_name="op_time", default=datetime.now, help_text='操作时间')

    class Meta:
        primary_key = CompositeKey('contract_market_code', 'date')
        indexes = (
            (('contract_market_code', 'date', 'symbol'), False),
        )
        table_name = 'cftc_disagg_future'
        database = mysql_db
        info = {'描述': 'CFTC数据 only Future Disagg', }
        table_settings = ["COMMENT='%s'" % (dict2str(info))]


class CFTCDisaggFutureOption(Model):
    date = DateField(column_name='date', help_text='统计日期')
    symbol = CharField(column_name='symbol', help_text='合约名称')
    contract_market_code = CharField(column_name='contract_market_code', null=False, help_text='合约代码')
    change_in_m_money_long_all = FloatField(column_name='change_in_m_money_long_all', null=True)
    change_in_m_money_short_all = FloatField(column_name='change_in_m_money_short_all', null=True)
    change_in_m_money_spread_all = FloatField(column_name='change_in_m_money_spread_all', null=True)
    change_in_nonrept_long_all = FloatField(column_name='change_in_nonrept_long_all', null=True)
    change_in_nonrept_short_all = FloatField(column_name='change_in_nonrept_short_all', null=True)
    change_in_open_interest_all = FloatField(column_name='change_in_open_Interest_all', null=True)
    change_in_other_rept_long_all = FloatField(column_name='change_in_other_rept_long_all', null=True)
    change_in_other_rept_short_all = FloatField(column_name='change_in_other_rept_short_all', null=True)
    change_in_other_rept_spread_all = FloatField(column_name='change_in_other_rept_spread_all', null=True)
    change_in_prod_merc_long_all = FloatField(column_name='change_in_prod_merc_long_all', null=True)
    change_in_prod_merc_short_all = FloatField(column_name='change_in_prod_merc_short_all', null=True)
    change_in_swap_long_all = FloatField(column_name='change_in_swap_long_all', null=True)
    change_in_swap_short_all = FloatField(column_name='change_in_swap_short_all', null=True)
    change_in_swap_spread_all = FloatField(column_name='change_in_swap_spread_all', null=True)
    change_in_tot_rept_long_all = FloatField(column_name='change_in_tot_rept_long_all', null=True)
    change_in_tot_rept_short_all = FloatField(column_name='change_in_tot_rept_short_all', null=True)
    conc_gross_le_4_tdr_long_all = FloatField(column_name='conc_gross_le_4_tdr_long_all', null=True)
    conc_gross_le_4_tdr_short_all = FloatField(column_name='conc_gross_le_4_tdr_short_all', null=True)
    conc_gross_le_8_tdr_long_all = FloatField(column_name='conc_gross_le_8_tdr_long_all', null=True)
    conc_gross_le_8_tdr_short_all = FloatField(column_name='conc_gross_le_8_tdr_short_all', null=True)
    conc_net_le_4_tdr_long_all = FloatField(column_name='conc_net_le_4_tdr_long_all', null=True)
    conc_net_le_4_tdr_short_all = FloatField(column_name='conc_net_le_4_tdr_short_all', null=True)
    conc_net_le_8_tdr_long_all = FloatField(column_name='conc_net_le_8_tdr_long_all', null=True)
    conc_net_le_8_tdr_short_all = FloatField(column_name='conc_net_le_8_tdr_short_all', null=True)
    m_money_positions_long_all = IntegerField(column_name='m_money_positions_long_all', null=True)
    m_money_positions_short_all = IntegerField(column_name='m_money_positions_short_all', null=True)
    m_money_positions_spread_all = IntegerField(column_name='m_money_positions_spread_all', null=True)
    nonrept_positions_long_all = IntegerField(column_name='nonrept_positions_long_all', null=True)
    nonrept_positions_short_all = IntegerField(column_name='nonrept_positions_short_all', null=True)
    open_interest_all = IntegerField(column_name='open_Interest_all', null=True)
    other_rept_positions_long_all = IntegerField(column_name='other_rept_positions_long_all', null=True)
    other_rept_positions_short_all = IntegerField(column_name='other_rept_positions_short_all', null=True)
    other_rept_positions_spread_all = IntegerField(column_name='other_rept_positions_spread_all', null=True)
    pct_of_oi_m_money_long_all = FloatField(column_name='pct_of_oi_m_money_long_all', null=True)
    pct_of_oi_m_money_short_all = FloatField(column_name='pct_of_oi_m_money_short_all', null=True)
    pct_of_oi_m_money_spread_all = FloatField(column_name='pct_of_oi_m_money_spread_all', null=True)
    pct_of_oi_nonrept_long_all = FloatField(column_name='pct_of_oi_nonrept_long_all', null=True)
    pct_of_oi_nonrept_short_all = FloatField(column_name='pct_of_oi_nonrept_short_all', null=True)
    pct_of_oi_other_rept_long_all = FloatField(column_name='pct_of_oi_other_rept_long_all', null=True)
    pct_of_oi_other_rept_short_all = FloatField(column_name='pct_of_oi_other_rept_short_all', null=True)
    pct_of_oi_other_rept_spread_all = FloatField(column_name='pct_of_oi_other_rept_spread_all', null=True)
    pct_of_oi_prod_merc_long_all = FloatField(column_name='pct_of_oi_prod_merc_long_all', null=True)
    pct_of_oi_prod_merc_short_all = FloatField(column_name='pct_of_oi_prod_merc_short_all', null=True)
    pct_of_oi_swap_long_all = FloatField(column_name='pct_of_oi_swap_long_all', null=True)
    pct_of_oi_swap_short_all = FloatField(column_name='pct_of_oi_swap_short_all', null=True)
    pct_of_oi_swap_spread_all = FloatField(column_name='pct_of_oi_swap_spread_all', null=True)
    pct_of_oi_tot_rept_long_all = FloatField(column_name='pct_of_oi_tot_rept_long_all', null=True)
    pct_of_oi_tot_rept_short_all = FloatField(column_name='pct_of_oi_tot_rept_short_all', null=True)
    pct_of_open_interest_all = IntegerField(column_name='pct_of_open_Interest_all', null=True)
    prod_merc_positions_long_all = IntegerField(column_name='prod_merc_positions_long_all', null=True)
    prod_merc_positions_short_all = IntegerField(column_name='prod_merc_positions_short_all', null=True)
    swap_positions_long_all = IntegerField(column_name='swap_positions_long_all', null=True)
    swap_positions_short_all = IntegerField(column_name='swap_positions_short_all', null=True)
    swap_positions_spread_all = IntegerField(column_name='swap_positions_spread_all', null=True)
    tot_rept_positions_long_all = IntegerField(column_name='tot_rept_positions_long_all', null=True)
    tot_rept_positions_short_all = IntegerField(column_name='tot_rept_positions_short_all', null=True)
    traders_m_money_long_all = FloatField(column_name='traders_m_money_long_all', null=True)
    traders_m_money_short_all = FloatField(column_name='traders_m_money_short_all', null=True)
    traders_m_money_spread_all = FloatField(column_name='traders_m_money_spread_all', null=True)
    traders_other_rept_long_all = FloatField(column_name='traders_other_rept_long_all', null=True)
    traders_other_rept_short_all = FloatField(column_name='traders_other_rept_short_all', null=True)
    traders_other_rept_spread_all = FloatField(column_name='traders_other_rept_spread_all', null=True)
    traders_prod_merc_long_all = FloatField(column_name='traders_prod_merc_long_all', null=True)
    traders_prod_merc_short_all = FloatField(column_name='traders_prod_merc_short_all', null=True)
    traders_swap_long_all = FloatField(column_name='traders_swap_long_all', null=True)
    traders_swap_short_all = FloatField(column_name='traders_swap_short_all', null=True)
    traders_swap_spread_all = FloatField(column_name='traders_swap_spread_all', null=True)
    traders_tot_all = IntegerField(column_name='traders_tot_all', null=True)
    traders_tot_rept_long_all = IntegerField(column_name='traders_tot_rept_long_all', null=True)
    traders_tot_rept_short_all = IntegerField(column_name='traders_tot_rept_short_all', null=True)
    op_time = DateTimeField(column_name="op_time", default=datetime.now, help_text='操作时间')

    class Meta:
        primary_key = CompositeKey('contract_market_code', 'date')
        indexes = (
            (('contract_market_code', 'date', 'symbol'), False),
        )
        table_name = 'cftc_disagg_future_option'
        database = mysql_db
        info = {'描述': 'CFTC数据 Future Option Disagg', }
        table_settings = ["COMMENT='%s'" % (dict2str(info))]


class CFTCReportFuture(Model):
    date = DateField(column_name='date', help_text='统计日期')
    symbol = CharField(column_name='symbol', help_text='合约名称')
    contract_market_code = CharField(column_name='contract_market_code', null=False, help_text='合约代码')
    change_in_comm_long_all = FloatField(column_name='change_in_comm_long_all', null=True)
    change_in_comm_short_all = FloatField(column_name='change_in_comm_short_all', null=True)
    change_in_noncomm_long_all = FloatField(column_name='change_in_noncomm_long_all', null=True)
    change_in_noncomm_short_all = FloatField(column_name='change_in_noncomm_short_all', null=True)
    change_in_noncomm_spead_all = FloatField(column_name='change_in_noncomm_spead_all', null=True)
    change_in_nonrept_long_all = FloatField(column_name='change_in_nonrept_long_all', null=True)
    change_in_nonrept_short_all = FloatField(column_name='change_in_nonrept_short_all', null=True)
    change_in_open_interest_all = FloatField(column_name='change_in_open_Interest_all', null=True)
    change_in_tot_rept_long_all = FloatField(column_name='change_in_tot_rept_long_all', null=True)
    change_in_tot_rept_short_all = FloatField(column_name='change_in_tot_rept_short_all', null=True)
    comm_positions_long_all = IntegerField(column_name='comm_positions_long_all', null=True)
    comm_positions_short_all = IntegerField(column_name='comm_positions_short_all', null=True)
    conc_gross_le_4_tdr_long_all = FloatField(column_name='conc_gross_le_4_tdr_long_all', null=True)
    conc_gross_le_4_tdr_short_all = FloatField(column_name='conc_gross_le_4_tdr_short_all', null=True)
    conc_gross_le_8_tdr_long_all = FloatField(column_name='conc_gross_le_8_tdr_long_all', null=True)
    conc_gross_le_8_tdr_short_all = FloatField(column_name='conc_gross_le_8_tdr_short_all', null=True)
    conc_net_le_4_tdr_long_all = FloatField(column_name='conc_net_le_4_tdr_long_all', null=True)
    conc_net_le_4_tdr_short_all = FloatField(column_name='conc_net_le_4_tdr_short_all', null=True)
    conc_net_le_8_tdr_long_all = FloatField(column_name='conc_net_le_8_tdr_long_all', null=True)
    conc_net_le_8_tdr_short_all = FloatField(column_name='conc_net_le_8_tdr_short_all', null=True)
    noncomm_positions_long_all = IntegerField(column_name='noncomm_positions_long_all', null=True)
    noncomm_positions_short_all = IntegerField(column_name='noncomm_positions_short_all', null=True)
    noncomm_postions_spread_all = IntegerField(column_name='noncomm_postions_spread_all', null=True)
    nonrept_positions_long_all = IntegerField(column_name='nonrept_positions_long_all', null=True)
    nonrept_positions_short_all = IntegerField(column_name='nonrept_positions_short_all', null=True)
    open_interest_all = IntegerField(column_name='open_Interest_all', null=True)
    pct_of_oi_comm_long_all = FloatField(column_name='pct_of_oi_comm_long_all', null=True)
    pct_of_oi_comm_short_all = FloatField(column_name='pct_of_oi_comm_short_all', null=True)
    pct_of_oi_noncomm_long_all = FloatField(column_name='pct_of_oi_noncomm_long_all', null=True)
    pct_of_oi_noncomm_short_all = FloatField(column_name='pct_of_oi_noncomm_short_all', null=True)
    pct_of_oi_noncomm_spread_all = FloatField(column_name='pct_of_oi_noncomm_spread_all', null=True)
    pct_of_oi_nonrept_long_all = FloatField(column_name='pct_of_oi_nonrept_long_all', null=True)
    pct_of_oi_nonrept_short_all = FloatField(column_name='pct_of_oi_nonrept_short_all', null=True)
    pct_of_oi_tot_rept_long_all = FloatField(column_name='pct_of_oi_tot_rept_long_all', null=True)
    pct_of_oi_tot_rept_short_all = FloatField(column_name='pct_of_oi_tot_rept_short_all', null=True)
    pct_of_open_interest_all = IntegerField(column_name='pct_of_open_Interest_all', null=True)
    tot_rept_positions_long_all = IntegerField(column_name='tot_rept_positions_long_all', null=True)
    tot_rept_positions_short_all = IntegerField(column_name='tot_rept_positions_short_all', null=True)
    traders_comm_long_all = IntegerField(column_name='traders_comm_long_all', null=True)
    traders_comm_short_all = IntegerField(column_name='traders_comm_short_all', null=True)
    traders_noncomm_long_all = IntegerField(column_name='traders_noncomm_long_all', null=True)
    traders_noncomm_short_all = IntegerField(column_name='traders_noncomm_short_all', null=True)
    traders_noncomm_spread_all = IntegerField(column_name='traders_noncomm_spread_all', null=True)
    traders_tot_all = IntegerField(column_name='traders_tot_all', null=True)
    traders_tot_rept_long_all = IntegerField(column_name='traders_tot_rept_long_all', null=True)
    traders_tot_rept_short_all = IntegerField(column_name='traders_tot_rept_short_all', null=True)
    op_time = DateTimeField(column_name="op_time", default=datetime.now, help_text='操作时间')

    class Meta:
        primary_key = CompositeKey('contract_market_code', 'date')
        indexes = (
            (('contract_market_code', 'date', 'symbol'), False),
        )
        table_name = 'cftc_report_future'
        database = mysql_db
        info = {'描述': 'CFTC数据 only Future Report', }
        table_settings = ["COMMENT='%s'" % (dict2str(info))]


class CFTCReportFutureOption(Model):
    date = DateField(column_name='date', help_text='统计日期')
    symbol = CharField(column_name='symbol', help_text='合约名称')
    contract_market_code = CharField(column_name='contract_market_code', help_text='合约代码')
    change_in_comm_long_all = FloatField(column_name='change_in_comm_long_all', null=True)
    change_in_comm_short_all = FloatField(column_name='change_in_comm_short_all', null=True)
    change_in_noncomm_long_all = FloatField(column_name='change_in_noncomm_long_all', null=True)
    change_in_noncomm_short_all = FloatField(column_name='change_in_noncomm_short_all', null=True)
    change_in_noncomm_spead_all = FloatField(column_name='change_in_noncomm_spead_all', null=True)
    change_in_nonrept_long_all = FloatField(column_name='change_in_nonrept_long_all', null=True)
    change_in_nonrept_short_all = FloatField(column_name='change_in_nonrept_short_all', null=True)
    change_in_open_interest_all = FloatField(column_name='change_in_open_Interest_all', null=True)
    change_in_tot_rept_long_all = FloatField(column_name='change_in_tot_rept_long_all', null=True)
    change_in_tot_rept_short_all = FloatField(column_name='change_in_tot_rept_short_all', null=True)
    comm_positions_long_all = IntegerField(column_name='comm_positions_long_all', null=True)
    comm_positions_short_all = IntegerField(column_name='comm_positions_short_all', null=True)
    conc_gross_le_4_tdr_long_all = FloatField(column_name='conc_gross_le_4_tdr_long_all', null=True)
    conc_gross_le_4_tdr_short_all = FloatField(column_name='conc_gross_le_4_tdr_short_all', null=True)
    conc_gross_le_8_tdr_long_all = FloatField(column_name='conc_gross_le_8_tdr_long_all', null=True)
    conc_gross_le_8_tdr_short_all = FloatField(column_name='conc_gross_le_8_tdr_short_all', null=True)
    conc_net_le_4_tdr_long_all = FloatField(column_name='conc_net_le_4_tdr_long_all', null=True)
    conc_net_le_4_tdr_short_all = FloatField(column_name='conc_net_le_4_tdr_short_all', null=True)
    conc_net_le_8_tdr_long_all = FloatField(column_name='conc_net_le_8_tdr_long_all', null=True)
    conc_net_le_8_tdr_short_all = FloatField(column_name='conc_net_le_8_tdr_short_all', null=True)
    noncomm_positions_long_all = IntegerField(column_name='noncomm_positions_long_all', null=True)
    noncomm_positions_short_all = IntegerField(column_name='noncomm_positions_short_all', null=True)
    noncomm_postions_spread_all = IntegerField(column_name='noncomm_postions_spread_all', null=True)
    nonrept_positions_long_all = IntegerField(column_name='nonrept_positions_long_all', null=True)
    nonrept_positions_short_all = IntegerField(column_name='nonrept_positions_short_all', null=True)
    open_interest_all = IntegerField(column_name='open_Interest_all', null=True)
    pct_of_oi_comm_long_all = FloatField(column_name='pct_of_oi_comm_long_all', null=True)
    pct_of_oi_comm_short_all = FloatField(column_name='pct_of_oi_comm_short_all', null=True)
    pct_of_oi_noncomm_long_all = FloatField(column_name='pct_of_oi_noncomm_long_all', null=True)
    pct_of_oi_noncomm_short_all = FloatField(column_name='pct_of_oi_noncomm_short_all', null=True)
    pct_of_oi_noncomm_spread_all = FloatField(column_name='pct_of_oi_noncomm_spread_all', null=True)
    pct_of_oi_nonrept_long_all = FloatField(column_name='pct_of_oi_nonrept_long_all', null=True)
    pct_of_oi_nonrept_short_all = FloatField(column_name='pct_of_oi_nonrept_short_all', null=True)
    pct_of_oi_tot_rept_long_all = FloatField(column_name='pct_of_oi_tot_rept_long_all', null=True)
    pct_of_oi_tot_rept_short_all = FloatField(column_name='pct_of_oi_tot_rept_short_all', null=True)
    pct_of_open_interest_all = IntegerField(column_name='pct_of_open_Interest_all', null=True)
    tot_rept_positions_long_all = IntegerField(column_name='tot_rept_positions_long_all', null=True)
    tot_rept_positions_short_all = IntegerField(column_name='tot_rept_positions_short_all', null=True)
    traders_comm_long_all = IntegerField(column_name='traders_comm_long_all', null=True)
    traders_comm_short_all = IntegerField(column_name='traders_comm_short_all', null=True)
    traders_noncomm_long_all = IntegerField(column_name='traders_noncomm_long_all', null=True)
    traders_noncomm_short_all = IntegerField(column_name='traders_noncomm_short_all', null=True)
    traders_noncomm_spread_all = IntegerField(column_name='traders_noncomm_spread_all', null=True)
    traders_tot_all = IntegerField(column_name='traders_tot_all', null=True)
    traders_tot_rept_long_all = IntegerField(column_name='traders_tot_rept_long_all', null=True)
    traders_tot_rept_short_all = IntegerField(column_name='traders_tot_rept_short_all', null=True)
    op_time = DateTimeField(column_name="op_time", default=datetime.now, help_text='操作时间')

    class Meta:
        primary_key = CompositeKey('contract_market_code', 'date')
        indexes = (
            (('contract_market_code', 'date', 'symbol'), False),
        )
        table_name = 'cftc_report_future_option'
        database = mysql_db
        info = {'描述': 'CFTC数据 Future Option Report', }
        table_settings = ["COMMENT='%s'" % (dict2str(info))]


class CFTCTradersFuture(Model):
    date = DateField(column_name='date', help_text='统计日期')
    symbol = CharField(column_name='symbol', help_text='合约名称')
    contract_market_code = CharField(column_name='contract_market_code', help_text='合约代码')
    asset_mgr_positions_long_all = IntegerField(column_name='asset_mgr_positions_long_all', null=True)
    asset_mgr_positions_short_all = IntegerField(column_name='asset_mgr_positions_short_all', null=True)
    asset_mgr_positions_spread_all = IntegerField(column_name='asset_mgr_positions_spread_all', null=True)
    change_in_asset_mgr_long_all = FloatField(column_name='change_in_asset_mgr_long_all', null=True)
    change_in_asset_mgr_short_all = FloatField(column_name='change_in_asset_mgr_short_all', null=True)
    change_in_asset_mgr_spread_all = FloatField(column_name='change_in_asset_mgr_spread_all', null=True)
    change_in_dealer_long_all = FloatField(column_name='change_in_dealer_long_all', null=True)
    change_in_dealer_short_all = FloatField(column_name='change_in_dealer_short_all', null=True)
    change_in_dealer_spread_all = FloatField(column_name='change_in_dealer_spread_all', null=True)
    change_in_lev_money_long_all = FloatField(column_name='change_in_lev_money_long_all', null=True)
    change_in_lev_money_short_all = FloatField(column_name='change_in_lev_money_short_all', null=True)
    change_in_lev_money_spread_all = FloatField(column_name='change_in_lev_money_spread_all', null=True)
    change_in_nonrept_long_all = FloatField(column_name='change_in_nonrept_long_all', null=True)
    change_in_nonrept_short_all = FloatField(column_name='change_in_nonrept_short_all', null=True)
    change_in_open_interest_all = FloatField(column_name='change_in_open_Interest_all', null=True)
    change_in_other_rept_long_all = FloatField(column_name='change_in_other_rept_long_all', null=True)
    change_in_other_rept_short_all = FloatField(column_name='change_in_other_rept_short_all', null=True)
    change_in_other_rept_spread_all = FloatField(column_name='change_in_other_rept_spread_all', null=True)
    change_in_tot_rept_long_all = FloatField(column_name='change_in_tot_rept_long_all', null=True)
    change_in_tot_rept_short_all = FloatField(column_name='change_in_tot_rept_short_all', null=True)
    conc_gross_le_4_tdr_long_all = FloatField(column_name='conc_gross_le_4_tdr_long_all', null=True)
    conc_gross_le_4_tdr_short_all = FloatField(column_name='conc_gross_le_4_tdr_short_all', null=True)
    conc_gross_le_8_tdr_long_all = FloatField(column_name='conc_gross_le_8_tdr_long_all', null=True)
    conc_gross_le_8_tdr_short_all = FloatField(column_name='conc_gross_le_8_tdr_short_all', null=True)
    conc_net_le_4_tdr_long_all = FloatField(column_name='conc_net_le_4_tdr_long_all', null=True)
    conc_net_le_4_tdr_short_all = FloatField(column_name='conc_net_le_4_tdr_short_all', null=True)
    conc_net_le_8_tdr_long_all = FloatField(column_name='conc_net_le_8_tdr_long_all', null=True)
    conc_net_le_8_tdr_short_all = FloatField(column_name='conc_net_le_8_tdr_short_all', null=True)
    dealer_positions_long_all = IntegerField(column_name='dealer_positions_long_all', null=True)
    dealer_positions_short_all = IntegerField(column_name='dealer_positions_short_all', null=True)
    dealer_positions_spread_all = IntegerField(column_name='dealer_positions_spread_all', null=True)
    lev_money_positions_long_all = IntegerField(column_name='lev_money_positions_long_all', null=True)
    lev_money_positions_short_all = IntegerField(column_name='lev_money_positions_short_all', null=True)
    lev_money_positions_spread_all = IntegerField(column_name='lev_money_positions_spread_all', null=True)
    nonrept_positions_long_all = IntegerField(column_name='nonrept_positions_long_all', null=True)
    nonrept_positions_short_all = IntegerField(column_name='nonrept_positions_short_all', null=True)
    open_interest_all = IntegerField(column_name='open_Interest_all', null=True)
    other_rept_positions_long_all = IntegerField(column_name='other_rept_positions_long_all', null=True)
    other_rept_positions_short_all = IntegerField(column_name='other_rept_positions_short_all', null=True)
    other_rept_positions_spread_all = IntegerField(column_name='other_rept_positions_spread_all', null=True)
    pct_of_oi_asset_mgr_long_all = FloatField(column_name='pct_of_oi_asset_mgr_long_all', null=True)
    pct_of_oi_asset_mgr_short_all = FloatField(column_name='pct_of_oi_asset_mgr_short_all', null=True)
    pct_of_oi_asset_mgr_spread_all = FloatField(column_name='pct_of_oi_asset_mgr_spread_all', null=True)
    pct_of_oi_dealer_long_all = FloatField(column_name='pct_of_oi_dealer_long_all', null=True)
    pct_of_oi_dealer_short_all = FloatField(column_name='pct_of_oi_dealer_short_all', null=True)
    pct_of_oi_dealer_spread_all = FloatField(column_name='pct_of_oi_dealer_spread_all', null=True)
    pct_of_oi_lev_money_long_all = FloatField(column_name='pct_of_oi_lev_money_long_all', null=True)
    pct_of_oi_lev_money_short_all = FloatField(column_name='pct_of_oi_lev_money_short_all', null=True)
    pct_of_oi_lev_money_spread_all = FloatField(column_name='pct_of_oi_lev_money_spread_all', null=True)
    pct_of_oi_nonrept_long_all = FloatField(column_name='pct_of_oi_nonrept_long_all', null=True)
    pct_of_oi_nonrept_short_all = FloatField(column_name='pct_of_oi_nonrept_short_all', null=True)
    pct_of_oi_other_rept_long_all = FloatField(column_name='pct_of_oi_other_rept_long_all', null=True)
    pct_of_oi_other_rept_short_all = FloatField(column_name='pct_of_oi_other_rept_short_all', null=True)
    pct_of_oi_other_rept_spread_all = FloatField(column_name='pct_of_oi_other_rept_spread_all', null=True)
    pct_of_oi_tot_rept_long_all = FloatField(column_name='pct_of_oi_tot_rept_long_all', null=True)
    pct_of_oi_tot_rept_short_all = FloatField(column_name='pct_of_oi_tot_rept_short_all', null=True)
    pct_of_open_interest_all = IntegerField(column_name='pct_of_open_Interest_all', null=True)
    tot_rept_positions_long_all = IntegerField(column_name='tot_rept_positions_long_all', null=True)
    tot_rept_positions_short_all = IntegerField(column_name='tot_rept_positions_short_all', null=True)
    traders_asset_mgr_long_all = FloatField(column_name='traders_asset_mgr_long_all', null=True)
    traders_asset_mgr_short_all = FloatField(column_name='traders_asset_mgr_short_all', null=True)
    traders_asset_mgr_spread_all = FloatField(column_name='traders_asset_mgr_spread_all', null=True)
    traders_dealer_long_all = FloatField(column_name='traders_dealer_long_all', null=True)
    traders_dealer_short_all = FloatField(column_name='traders_dealer_short_all', null=True)
    traders_dealer_spread_all = FloatField(column_name='traders_dealer_spread_all', null=True)
    traders_lev_money_long_all = FloatField(column_name='traders_lev_money_long_all', null=True)
    traders_lev_money_short_all = FloatField(column_name='traders_lev_money_short_all', null=True)
    traders_lev_money_spread_all = FloatField(column_name='traders_lev_money_spread_all', null=True)
    traders_other_rept_long_all = FloatField(column_name='traders_other_rept_long_all', null=True)
    traders_other_rept_short_all = FloatField(column_name='traders_other_rept_short_all', null=True)
    traders_other_rept_spread_all = FloatField(column_name='traders_other_rept_spread_all', null=True)
    traders_tot_all = IntegerField(column_name='traders_tot_all', null=True)
    traders_tot_rept_long_all = IntegerField(column_name='traders_tot_rept_long_all', null=True)
    traders_tot_rept_short_all = FloatField(column_name='traders_tot_rept_short_all', null=True)
    op_time = DateTimeField(column_name="op_time", default=datetime.now, help_text='操作时间')

    class Meta:
        primary_key = CompositeKey('contract_market_code', 'date')
        indexes = (
            (('contract_market_code', 'date', 'symbol'), False),
        )
        table_name = 'cftc_traders_future'
        database = mysql_db
        info = {'描述': 'CFTC数据 only Future Traders', }
        table_settings = ["COMMENT='%s'" % (dict2str(info))]


class CFTCTradersFutureOption(Model):
    date = DateField(column_name='date', help_text='统计日期')
    symbol = CharField(column_name='symbol', help_text='合约名称')
    contract_market_code = CharField(column_name='contract_market_code', null=False, help_text='合约代码')
    asset_mgr_positions_long_all = IntegerField(column_name='asset_mgr_positions_long_all', null=True)
    asset_mgr_positions_short_all = IntegerField(column_name='asset_mgr_positions_short_all', null=True)
    asset_mgr_positions_spread_all = IntegerField(column_name='asset_mgr_positions_spread_all', null=True)
    change_in_asset_mgr_long_all = FloatField(column_name='change_in_asset_mgr_long_all', null=True)
    change_in_asset_mgr_short_all = FloatField(column_name='change_in_asset_mgr_short_all', null=True)
    change_in_asset_mgr_spread_all = FloatField(column_name='change_in_asset_mgr_spread_all', null=True)
    change_in_dealer_long_all = FloatField(column_name='change_in_dealer_long_all', null=True)
    change_in_dealer_short_all = FloatField(column_name='change_in_dealer_short_all', null=True)
    change_in_dealer_spread_all = FloatField(column_name='change_in_dealer_spread_all', null=True)
    change_in_lev_money_long_all = FloatField(column_name='change_in_lev_money_long_all', null=True)
    change_in_lev_money_short_all = FloatField(column_name='change_in_lev_money_short_all', null=True)
    change_in_lev_money_spread_all = FloatField(column_name='change_in_lev_money_spread_all', null=True)
    change_in_nonrept_long_all = FloatField(column_name='change_in_nonrept_long_all', null=True)
    change_in_nonrept_short_all = FloatField(column_name='change_in_nonrept_short_all', null=True)
    change_in_open_interest_all = FloatField(column_name='change_in_open_Interest_all', null=True)
    change_in_other_rept_long_all = FloatField(column_name='change_in_other_rept_long_all', null=True)
    change_in_other_rept_short_all = FloatField(column_name='change_in_other_rept_short_all', null=True)
    change_in_other_rept_spread_all = FloatField(column_name='change_in_other_rept_spread_all', null=True)
    change_in_tot_rept_long_all = FloatField(column_name='change_in_tot_rept_long_all', null=True)
    change_in_tot_rept_short_all = FloatField(column_name='change_in_tot_rept_short_all', null=True)
    conc_gross_le_4_tdr_long_all = FloatField(column_name='conc_gross_le_4_tdr_long_all', null=True)
    conc_gross_le_4_tdr_short_all = FloatField(column_name='conc_gross_le_4_tdr_short_all', null=True)
    conc_gross_le_8_tdr_long_all = FloatField(column_name='conc_gross_le_8_tdr_long_all', null=True)
    conc_gross_le_8_tdr_short_all = FloatField(column_name='conc_gross_le_8_tdr_short_all', null=True)
    conc_net_le_4_tdr_long_all = FloatField(column_name='conc_net_le_4_tdr_long_all', null=True)
    conc_net_le_4_tdr_short_all = FloatField(column_name='conc_net_le_4_tdr_short_all', null=True)
    conc_net_le_8_tdr_long_all = FloatField(column_name='conc_net_le_8_tdr_long_all', null=True)
    conc_net_le_8_tdr_short_all = FloatField(column_name='conc_net_le_8_tdr_short_all', null=True)
    dealer_positions_long_all = IntegerField(column_name='dealer_positions_long_all', null=True)
    dealer_positions_short_all = IntegerField(column_name='dealer_positions_short_all', null=True)
    dealer_positions_spread_all = IntegerField(column_name='dealer_positions_spread_all', null=True)
    lev_money_positions_long_all = IntegerField(column_name='lev_money_positions_long_all', null=True)
    lev_money_positions_short_all = IntegerField(column_name='lev_money_positions_short_all', null=True)
    lev_money_positions_spread_all = IntegerField(column_name='lev_money_positions_spread_all', null=True)
    nonrept_positions_long_all = IntegerField(column_name='nonrept_positions_long_all', null=True)
    nonrept_positions_short_all = IntegerField(column_name='nonrept_positions_short_all', null=True)
    open_interest_all = IntegerField(column_name='open_Interest_all', null=True)
    other_rept_positions_long_all = IntegerField(column_name='other_rept_positions_long_all', null=True)
    other_rept_positions_short_all = IntegerField(column_name='other_rept_positions_short_all', null=True)
    other_rept_positions_spread_all = IntegerField(column_name='other_rept_positions_spread_all', null=True)
    pct_of_oi_asset_mgr_long_all = FloatField(column_name='pct_of_oi_asset_mgr_long_all', null=True)
    pct_of_oi_asset_mgr_short_all = FloatField(column_name='pct_of_oi_asset_mgr_short_all', null=True)
    pct_of_oi_asset_mgr_spread_all = FloatField(column_name='pct_of_oi_asset_mgr_spread_all', null=True)
    pct_of_oi_dealer_long_all = FloatField(column_name='pct_of_oi_dealer_long_all', null=True)
    pct_of_oi_dealer_short_all = FloatField(column_name='pct_of_oi_dealer_short_all', null=True)
    pct_of_oi_dealer_spread_all = FloatField(column_name='pct_of_oi_dealer_spread_all', null=True)
    pct_of_oi_lev_money_long_all = FloatField(column_name='pct_of_oi_lev_money_long_all', null=True)
    pct_of_oi_lev_money_short_all = FloatField(column_name='pct_of_oi_lev_money_short_all', null=True)
    pct_of_oi_lev_money_spread_all = FloatField(column_name='pct_of_oi_lev_money_spread_all', null=True)
    pct_of_oi_nonrept_long_all = FloatField(column_name='pct_of_oi_nonrept_long_all', null=True)
    pct_of_oi_nonrept_short_all = FloatField(column_name='pct_of_oi_nonrept_short_all', null=True)
    pct_of_oi_other_rept_long_all = FloatField(column_name='pct_of_oi_other_rept_long_all', null=True)
    pct_of_oi_other_rept_short_all = FloatField(column_name='pct_of_oi_other_rept_short_all', null=True)
    pct_of_oi_other_rept_spread_all = FloatField(column_name='pct_of_oi_other_rept_spread_all', null=True)
    pct_of_oi_tot_rept_long_all = FloatField(column_name='pct_of_oi_tot_rept_long_all', null=True)
    pct_of_oi_tot_rept_short_all = FloatField(column_name='pct_of_oi_tot_rept_short_all', null=True)
    pct_of_open_interest_all = IntegerField(column_name='pct_of_open_Interest_all', null=True)
    tot_rept_positions_long_all = IntegerField(column_name='tot_rept_positions_long_all', null=True)
    tot_rept_positions_short_all = IntegerField(column_name='tot_rept_positions_short_all', null=True)
    traders_asset_mgr_long_all = FloatField(column_name='traders_asset_mgr_long_all', null=True)
    traders_asset_mgr_short_all = FloatField(column_name='traders_asset_mgr_short_all', null=True)
    traders_asset_mgr_spread_all = FloatField(column_name='traders_asset_mgr_spread_all', null=True)
    traders_dealer_long_all = FloatField(column_name='traders_dealer_long_all', null=True)
    traders_dealer_short_all = FloatField(column_name='traders_dealer_short_all', null=True)
    traders_dealer_spread_all = FloatField(column_name='traders_dealer_spread_all', null=True)
    traders_lev_money_long_all = FloatField(column_name='traders_lev_money_long_all', null=True)
    traders_lev_money_short_all = FloatField(column_name='traders_lev_money_short_all', null=True)
    traders_lev_money_spread_all = FloatField(column_name='traders_lev_money_spread_all', null=True)
    traders_other_rept_long_all = FloatField(column_name='traders_other_rept_long_all', null=True)
    traders_other_rept_short_all = FloatField(column_name='traders_other_rept_short_all', null=True)
    traders_other_rept_spread_all = FloatField(column_name='traders_other_rept_spread_all', null=True)
    traders_tot_all = IntegerField(column_name='traders_tot_all', null=True)
    traders_tot_rept_long_all = IntegerField(column_name='traders_tot_rept_long_all', null=True)
    traders_tot_rept_short_all = FloatField(column_name='traders_tot_rept_short_all', null=True)
    op_time = DateTimeField(column_name="op_time", default=datetime.now, help_text='操作时间')

    class Meta:
        primary_key = CompositeKey('contract_market_code', 'date')
        indexes = (
            (('contract_market_code', 'date', 'symbol'), False),
        )
        table_name = 'cftc_traders_future_option'
        database = mysql_db
        info = {'描述': 'CFTC数据 Future Option Traders', }
        table_settings = ["COMMENT='%s'" % (dict2str(info))]


class CFTCReference(Model):
    code = CharField(column_name='code', primary_key=True, help_text='CFTC代码')
    symbol = CharField(column_name='symbol', help_text='期货合约代码')
    name = CharField(column_name='name', null=True, help_text='合约名称1')
    cname = CharField(column_name='cname', null=True, help_text='中文名称')
    type = CharField(column_name='type', null=True, help_text='分类')
    name2 = CharField(column_name='name2', null=True, help_text='合约名称2')
    name3 = CharField(column_name='name3', null=True, help_text='合约名称3')
    name4 = CharField(column_name='name4', null=True, help_text='合约名称4')
    name5 = CharField(column_name='name5', null=True, help_text='合约名称5')

    class Meta:
        table_name = 'cftc_reference'
        database = mysql_db
        info = {'描述': 'CFTC代码对照表', }
        table_settings = ["COMMENT='%s'" % (dict2str(info))]


if __name__ == '__main__':
    handle_table(CFTCDisaggFuture, 1)
    handle_table(CFTCDisaggFutureOption, 1)
    handle_table(CFTCReportFuture, 1)
    handle_table(CFTCReportFutureOption, 1)
    handle_table(CFTCTradersFuture, 1)
    handle_table(CFTCTradersFutureOption, 1)
